version: '3'
services:
  jpa_tests_postgres_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: jpa_tests_postgres_db
    ports:
      - "5432:5432"